# These are supported funding model platforms

github: https://github.com/sponsors/imgnxorg
patreon: https://patreon.com/imgnx
open_collective: https://opencollective.com/imgnx
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # I am a Managed Service Provider (MSP) offering tailored technology solutions to businesses and organizations, focusing on optimizing IT systems, security, and scalability.

Passionate about non-profit STEM initiatives and fostering open-source innovation, I actively contribute to and support projects that make technology accessible to everyone, particularly underserved communities.

Recognized among the GitHub Top 1%, I bring a commitment to excellence in coding, collaboration, and open-source contributions, consistently delivering impactful and high-quality solutions.

You can explore my work and collaborations on GitHub.Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: https://buymeacoffee.com/donaldmoore
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
