repos:
-   repo: https://github.com/gitguardian/ggshield
    rev: v1.18.1  # Use the latest version available
    hooks:
    -   id: ggshield
        language_version: python3
        stages: [pre-commit]
        entry: ggshield secret scan pre-commit

# Optional but recommended additional checks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
